// Mocks generated by Mockito 5.3.2 from annotations
// in login_test/test/modules/login/view/login_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i3;
import 'package:login_test/src/domain/entities/communication.dart' as _i2;
import 'package:login_test/src/domain/interface/login_view_model.dart' as _i4;
import 'package:login_test/src/domain/interface/show_snackbar.dart' as _i7;
import 'package:login_test/src/domain/interface/validator_login.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommunication_0<T> extends _i1.SmartFake
    implements _i2.Communication<T> {
  _FakeCommunication_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalKey<T> {
  _FakeGlobalKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILoginViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoginViewModel extends _i1.Mock implements _i4.ILoginViewModel {
  MockILoginViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Communication<dynamic>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i2.Communication<dynamic>>.value(
            _FakeCommunication_0<dynamic>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.Communication<dynamic>>);
}

/// A class which mocks [ILoginValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoginValidator extends _i1.Mock implements _i6.ILoginValidator {
  MockILoginValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GlobalKey<_i3.FormState> get formKeyLogin => (super.noSuchMethod(
        Invocation.getter(#formKeyLogin),
        returnValue: _FakeGlobalKey_1<_i3.FormState>(
          this,
          Invocation.getter(#formKeyLogin),
        ),
      ) as _i3.GlobalKey<_i3.FormState>);
  @override
  bool validate() => (super.noSuchMethod(
        Invocation.method(
          #validate,
          [],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [IShowSnackBar].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShowSnackBar extends _i1.Mock implements _i7.IShowSnackBar {
  MockIShowSnackBar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void show(String? message) => super.noSuchMethod(
        Invocation.method(
          #show,
          [message],
        ),
        returnValueForMissingStub: null,
      );
}
